spring:
  application:
    name: end-template
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    default: dev
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置

server:
  port: 7529
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.zzy: debug
    org.springframework: warn

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 30